// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/sabih15/TeleOpServer/internal/modules/user"
	"github.com/sabih15/TeleOpServer/internal/platform/config"
	"github.com/sabih15/TeleOpServer/internal/platform/database"
	"github.com/sabih15/TeleOpServer/internal/platform/server"
)

// Injectors from wire.go:

func InitializeApp() (*server.Server, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	db, err := database.NewPostgres(configConfig)
	if err != nil {
		return nil, err
	}
	repository := user.NewRepository(db)
	service := user.NewService(repository, configConfig)
	handler := user.NewHandler(service)
	serverServer := server.NewServer(configConfig, handler)
	return serverServer, nil
}
