// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"context"
	"github.com/sabih15/TeleOpServer/internal/modules/TOCommands"
	"github.com/sabih15/TeleOpServer/internal/modules/gps"
	"github.com/sabih15/TeleOpServer/internal/modules/user"
	"github.com/sabih15/TeleOpServer/internal/platform/config"
	"github.com/sabih15/TeleOpServer/internal/platform/database"
	"github.com/sabih15/TeleOpServer/internal/platform/mqttclient"
	"github.com/sabih15/TeleOpServer/internal/platform/server"
)

// Injectors from wire.go:

func InitializeApp(ctx context.Context) (*server.Server, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	db, err := database.NewPostgres(configConfig)
	if err != nil {
		return nil, err
	}
	client, err := mqttclient.New(configConfig)
	if err != nil {
		return nil, err
	}
	iRepository := user.NewRepository(db)
	iService := user.NewService(iRepository, configConfig)
	handler := user.NewHandler(iService)
	toCommandsIRepository := TOCommands.NewRepository(db)
	toCommandsIService := TOCommands.NewService(toCommandsIRepository)
	toCommandsHandler := TOCommands.NewHandler(toCommandsIService)
	consumer := TOCommands.NewConsumer(client, toCommandsIService)
	gpsIRepository := gps.NewRepository(db)
	gpsIService := gps.NewService(gpsIRepository)
	gpsConsumer := gps.NewConsumer(client, gpsIService)
	mux, err := provideRouter(ctx, configConfig, db, client, handler, toCommandsHandler, consumer, gpsConsumer)
	if err != nil {
		return nil, err
	}
	serverServer := server.NewServer(configConfig, mux)
	return serverServer, nil
}
